---
save_checkpoints: true
checkpoint_name: baseline.pth
checkpoint_dir: ../path/to/checkpoints
plot_dir: ../path/to/output
seed: 42

neptune_project_name: account_name/project_name
neptune_experiment: experiment_name
neptune_api_token: ABCD1234

architecture: unet
encoder_name: resnet34
encoder_weights: imagenet
use_batchnorm: true
pooling: avg
dropout: 0.4

device: cuda
workers: 4

loss: dice_loss
loss_weight: 0.8
combine: false
metrics:
  - name: dice_score
    type: segmentation
  - name: dice_loss
    type: segmentation
  - name: cross_entropy
    type: classification
  - name: accuracy
    type: classification
rounding: 0.5
ignore_channels: null

lr: 1.0e-4
epochs: 30
batch_size: 16
optimizer: adam
scheduler: cosine
max_round: 30
eta_min: 0.0
step_size: 15
gamma: 0.5

spacing: 2.0
patch_size: 256
verbose: true
normalize: simple
transform: light
eval_dir: ../path/to/transform

tissuemix: false
probability: 0.5
blending: false
warping: false
color: false

classes:
  - glomeruli

train_data: ../path/to/train/data_train.csv
valid_data: ../path/to/valid/data_valid.csv
...
